pool: Hosted Windows 2019 with VS2019

variables:
  marketplaceConnection: 'Marketplace luisfraile'
  publisher: luisfraile
  extensionid: esquio-extensions
  packagefile: '$(Build.ArtifactStagingDirectory)/Esquio-$(Extension.Version).vsix'


trigger:
  batch: true 
  paths:
    include: 
    - /extensions/azure-devops


steps:
- task: TfxInstaller@1
  inputs:
    version: 'v0.6.x'

- task: CmdLine@2
  displayName: TSC rollback feature
  inputs:
    script: 'echo Build (tsc) rollback feature
      tsc'
    workingDirectory: 'extensions/azure-devops/rollback-feature'
    failOnStderr: true

- task: CmdLine@2
  displayName: TSC rollout feature
  inputs:
    script: 'echo Build (tsc) rollout feature
      tsc'
    workingDirectory: 'extensions/azure-devops/rollout-feature'
    failOnStderr: true

- task: ExtensionVersion@1
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: '$(marketplaceConnection)'
    publisherId: '$(publisher)'
    extensionId: '$(extensionid)'
    versionAction: 'Patch'

- task: PackageVSTSExtension@1
  inputs:
    rootFolder: 'extensions/azure-devops'
    outputPath: '$(packagefile)'
    extensionVersion: '$(Extension.Version)'
    updateTasksVersion: false

- task: PublishExtension@1
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: '$(marketplaceConnection)'
    fileType: 'vsix'
    vsixFile: '$(packagefile)'
    updateTasksVersion: false

- task: 'b86cdd2a-0579-4d40-b28f-18197ffaf520@1'
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: '$(marketplaceConnection)'
    method: 'id'
    publisherId: '$(publisher)'
    extensionId: '$(extensionid)'
