pool: Hosted Windows 2019 with VS2019

variables:
  marketplaceConnection: 'Xabaril Marketplace'
  publisher: xabaril
  extensionid: esquio-extensions-canary
  packagefile: '$(Build.ArtifactStagingDirectory)/Esquio-$(Extension.Version)-canary.vsix'

trigger: none

steps:
- task: TfxInstaller@1
  inputs:
    version: 'v0.6.x'

- template: templates/azure-task-build-template.yml
  parameters:
    pathToExtension: 'extensions/azure-devops/rollback-feature/rollback-featureV1'
    taskName: rollback

- template: templates/azure-task-build-template.yml
  parameters:
    pathToExtension: 'extensions/azure-devops/rollout-feature/rollout-featureV1'
    taskName: rollout

- template: templates/azure-task-build-template.yml
  parameters:
    pathToExtension: 'extensions/azure-devops/set-toggle-parameter/set-toggle-parameterV1'
    taskName: 'set toggle parameter'

- template: templates/azure-task-build-template.yml
  parameters:
    pathToExtension: 'extensions/azure-devops/rollback-feature/rollback-featureV2'
    taskName: rollback

- template: templates/azure-task-build-template.yml
  parameters:
    pathToExtension: 'extensions/azure-devops/rollout-feature/rollout-featureV2'
    taskName: rollout

- template: templates/azure-task-build-template.yml
  parameters:
    pathToExtension: 'extensions/azure-devops/set-toggle-parameter/set-toggle-parameterV2'
    taskName: 'set toggle parameter'

- task: ExtensionVersion@1
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: '$(marketplaceConnection)'
    publisherId: '$(publisher)'
    extensionId: '$(extensionid)'
    versionAction: 'Patch'

- task: PackageVSTSExtension@1
  inputs:
    rootFolder: 'extensions/azure-devops'
    patternManifest: 'vss-extension-canary.json'
    outputPath: '$(packagefile)'
    extensionVersion: '$(Extension.Version)'
    updateTasksVersion: true
    updateTasksVersionType: 'patch'

- task: PublishExtension@1
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: '$(marketplaceConnection)'
    fileType: 'vsix'
    vsixFile: '$(packagefile)'
    updateTasksVersion: false
    extensionVisibility: 'private'

# - task: 'b86cdd2a-0579-4d40-b28f-18197ffaf520@1'
#   inputs:
#     connectTo: 'VsTeam'
#     connectedServiceName: '$(marketplaceConnection)'
#     method: 'id'
#     publisherId: '$(publisher)'
#     extensionId: '$(extensionid)'
