version: '3'
services:
    app:
        image: app
        container_name: app
        depends_on: 
            - sqlserver
            - ui
        ports:
            - 8060:80
        build:
            context: ..\..
            dockerfile: demos/AppWithUI/app-dockerfile
        environment:
            - EFSTORE=Y
            - ConnectionStrings__Esquio=Server=tcp:sqlserver,1433;Initial Catalog=Esquio;User Id=sa;Password=Password12!
    ui:
        image: ui
        container_name: ui
        depends_on: 
            - sqlserver
        ports:
            - 8090:80
        build:
            context: ..\..
            dockerfile: demos/AppWithUI/ui-dockerfile
        environment:
            - ConnectionStrings__Esquio=Server=tcp:sqlserver,1433;Initial Catalog=Esquio;User Id=sa;Password=Password12!
    sqlserver:
        image: microsoft/mssql-server-linux
        restart: always
        ports:
            - 1833:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12!
   