pr: none
trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  imageName: esquiodemoapp
  acrName: esquio.azurecr.io
  appName: esquioDemo
  dockerRepo: esquio
  
steps:
- task: Docker@0
  displayName: 'Build an image'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure'
    azureContainerRegistry: '$(acrName)'
    action: 'Build an image'
    dockerFile: 'demos\AppWithUI\app-dockerfile'
    defaultContext: false
    context: '$(Build.SourcesDirectory)'
    imageName: '$(imageName):$(Build.BuildId)'
    workingDirectory: '$(Build.SourcesDirectory)'



