trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  appImageName: esquiodemoapp
  uiImageName: esquiodemoui
  acrName: esquio.azurecr.io
  appWebAppName: esquiodemoapp
  uiWebAppName: esquiodemoui
  dockerRepo: esquio
  

steps:
- task: Docker@0
  displayName: 'Build app image'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure'
    azureContainerRegistry: '$(acrName)'
    action: 'Build an image'
    dockerFile: 'demos/AppWithUI/app-dockerfile'
    defaultContext: false
    context: '$(Build.SourcesDirectory)'
    imageName: '$(appImageName):$(Build.BuildId)'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Docker@0
  displayName: 'Build ui Image'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure'
    azureContainerRegistry: '$(acrName)'
    action: 'Build an image'
    dockerFile: 'demos/AppWithUI/ui-dockerfile'
    defaultContext: false
    context: '$(Build.SourcesDirectory)'
    imageName: '$(uiImageName):$(Build.BuildId)'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Docker@0
  displayName: 'Push app image'
  inputs:
    azureSubscription: 'Azure'
    azureContainerRegistry: $(acrName)
    action: 'Push an image'
    imageName: '$(appImageName):$(Build.BuildId)'

- task: Docker@0
  displayName: 'Push ui image'
  inputs:
    azureSubscription: 'Azure'
    azureContainerRegistry: $(acrName)
    action: 'Push an image'
    imageName: '$(uiImageName):$(Build.BuildId)'

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: $(appWebAppName)'
  inputs:
    azureSubscription: 'Azure'
    appType: applinux
    WebAppName: $(appWebAppName)
    DockerNamespace: $(acrName)
    DockerRepository: '$(appImageName)'
    DockerImageTag: '$(Build.BuildId)'
    AppSettings: '-EFStore "true"-ApplicationInsights__InstrumentationKey "$(appInsightsInstrumentationKey)" -ConnectionStrings__Esquio "$(sqlConnection)" -DOCKER_REGISTRY_SERVER_USERNAME "$(dockerRegistryUserName)" -DOCKER_REGISTRY_SERVER_URL "https://$(acrName)" -DOCKER_REGISTRY_SERVER_PASSWORD "$(dockerRegistryPassword)"'
    TakeAppOfflineFlag: true

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: $(uiImageName)'
  inputs:
    azureSubscription: 'Azure'
    appType: applinux
    WebAppName: $(uiImageName)
    DockerNamespace: $(acrName)
    DockerRepository: '$(uiImageName)'
    DockerImageTag: '$(Build.BuildId)'
    AppSettings: '-ConnectionStrings__Esquio "$(sqlConnection)" -DOCKER_REGISTRY_SERVER_USERNAME "$(dockerRegistryUserName)" -DOCKER_REGISTRY_SERVER_URL "https://$(acrName)" -DOCKER_REGISTRY_SERVER_PASSWORD "$(dockerRegistryPassword)"'
    TakeAppOfflineFlag: true

# - task: Docker@0
#   displayName: 'Build an image'
#   inputs:
#     azureSubscriptionEndpoint: Azure
#     azureContainerRegistry: $(acrName)
#     dockerFile: build/Dockerfile
#     defaultContext: false
#     context: '$(Build.SourcesDirectory)'
#     imageName: '$(imageName):$(Build.BuildId)'
#     workingDirectory: '$(Build.SourcesDirectory)'

# - task: Docker@0
#   displayName: 'Push an image'
#   inputs:
#     azureSubscription: 'Azure'
#     azureContainerRegistry: $(acrName)
#     action: 'Push an image'
#     imageName: '$(imageName):$(Build.BuildId)'

# - task: AzureRmWebAppDeployment@3
#   displayName: 'Azure App Service Deploy: demoesquiolf'
#   inputs:
#     azureSubscription: 'Azure'
#     appType: applinux
#     WebAppName: $(appName)
#     DockerNamespace: $(acrName)
#     DockerRepository: '$(imageName)'
#     DockerImageTag: '$(Build.BuildId)'
#     AppSettings: '-Data__EsquioConnectionString "$(sqlConnection)" -DOCKER_REGISTRY_SERVER_USERNAME "$(dockerRegistryUserName)" -DOCKER_REGISTRY_SERVER_URL "https://$(acrName)" -DOCKER_REGISTRY_SERVER_PASSWORD "$(dockerRegistryPassword)"'
#     TakeAppOfflineFlag: true




