# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

name: $(rev:r)
trigger:
    batch: true
    branches:
        include:
        - master
    paths:
        include:
        - src/*
        - tests/*

pool:
  name: Hosted Ubuntu 1604

resources:
  containers:
  - container: sqlserver
    image: microsoft/mssql-server-linux
    options: -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=Password12!"
    ports:
      - 1833:1433
services:
  sqlserver: sqlserver

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:
- task: UseDotNet@2
  displayName: 'install dotnet sdk'
  inputs:
    packageType: 'sdk'
    version: '3.0.100-preview8-013656'
    includePreviewVersions: true
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: '**/Esquio.sln'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    arguments: '--configuration $(buildConfiguration) --no-restore'
    projects: '**/Esquio.sln'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: test
    projects: '**/Esquio.sln'
- task: PublishTestResults@2
  displayName: 'publish tests results'
  inputs:
    testResultsFormat: 'XUnit'
    testResultsFiles: '/home/vsts/work/_temp/*.trx'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Esquio'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: './src/Esquio/Esquio.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'
    buildProperties: 'VersionSuffix=-preview.$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Esquio AspNetCore'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: './src/Esquio.AspNetCore/Esquio.AspNetCore.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'
    buildProperties: 'VersionSuffix=-preview.$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack Configuration Store'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: './src/Esquio.Configuration.Store/Esquio.Configuration.Store.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'
    buildProperties: 'VersionSuffix=-preview.$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack EF Core  Store'
  inputs:
    command: 'pack'
    feedsToUse: 'select'
    packagesToPack: './src/Esquio.EntityFrameworkCore.Store/Esquio.EntityFrameworkCore.Store.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: 'off'
    buildProperties: 'VersionSuffix=-preview.$(Build.BuildNumber)'
- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'packages'
    publishLocation: 'Container'
- task: NuGetCommand@2
  displayName: 'push package to MyGet Preview Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'MyGet Preview Feed'