trigger: none
pr: none 

variables:
  dockerUITagBase: '2.0'

pool:
  name: Hosted Ubuntu 1604

steps:
- task: Docker@2
  inputs:    
    containerRegistry: 'DockerHubXabaril'
    repository: 'xabarilcoding/esquioui'
    command: 'buildAndPush'
    Dockerfile: 'demos/AppWithUI/ui-dockerfile'
    buildContext: '$(Build.SourcesDirectory)'
    tags: |
      $(dockerUITagBase).$(Build.BuildId)
      latest