trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  appImageName: esquiodemoapp
  uiImageName: esquioui
  acrName: esquio.azurecr.io
  appWebAppName: esquiodemoapp
  uiWebAppName: esquiodemoui
  dockerRepo: esquio
  
  

steps:
- task: Docker@0
  displayName: 'Build ui Image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'DockerHubXabaril'
    action: 'Build an image'
    dockerFile: 'demos/AppWithUI/ui-dockerfile'
    defaultContext: false
    context: '$(Build.SourcesDirectory)'
    imageName: 'xabarilcoding/$(uiImageName):$(Build.BuildId)'
    workingDirectory: '$(Build.SourcesDirectory)'

- task: Docker@0
  displayName: 'Push ui image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'DockerHubXabaril'
    action: 'Push an image'
    imageName: 'xabarilcoding/$(uiImageName):$(Build.BuildId)'