version: '3'
services:
    app:
        image: app
        container_name: ui
        depends_on: 
            - sqlserver
        ports:
            - 5000:80
        build:
            context: ..\..
            dockerfile: demos/full/app-dockerfile
    sqlserver:
        image: microsoft/mssql-server-linux
        restart: always
        ports:
            - 1833:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Password12!
    # ui:
    #     image: esquioui
    #     container_name: ui
    #     depends_on:
    #         - sqlserver
    #     build:
    #         context: ..\..\..
    #         dockerfile: src/Magus.IdSrvr/Dockerfile
   