name: Esquio Continous Deployment
on: 
  push:
    tags:       
      - demo-release-*  # Push events to release-* 
jobs:
  build:
    env:
      BUILD_CONFIG: Release
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: dotnet build
      run: dotnet build ./src/Esquio.UI.Host/Esquio.UI.Host.csproj -c $BUILD_CONFIG
  docker:
    env:
      TAG: 3.0.${{ github.run_id }}
    needs: build
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: xabarilcoding/esquiodemo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ./build/DemoDockerfile
        tags: "latest,$TAG"