name: Esquio Nightly Build
on:
  push:
    branches: 
      - master
jobs:
  build:
    env:
      BUILD_CONFIG: Release

    name: Build
    runs-on: ubuntu-latest
    services:
      sql-server:
        image: microsoft/mssql-server-linux
        env:
          ACCEPT_EULA: Y
          MSSQL_SA_PASSWORD: Password12!
        ports:
        - 5433:1433
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.0.0
      with:
        version: 3.1.100
    - name: dotnet build
      run: dotnet build Esquio.sln -c $BUILD_CONFIG
    - name: dotnet test [UnitTests]
      run: dotnet test ./tests/UnitTests/UnitTests.csproj -c $BUILD_CONFIG --no-build
    - name: dotnet test [FunctionalTests]
      run: dotnet test ./tests/FunctionalTests/FunctionalTests.csproj -c $BUILD_CONFIG --no-build
    - name: dotnet pack [Esquio]
      run: dotnet pack ./src/Esquio/Esquio.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
    - name: dotnet pack [Esquio.AspNetCore]
      run: dotnet pack ./src/Esquio.AspNetCore/Esquio.AspNetCore.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
    - name: dotnet pack [Esquio.AspNetCore.ApplicationInsightProcessor]
      run: dotnet pack ./src/Esquio.AspNetCore.ApplicationInsightProcessor/Esquio.AspNetCore.ApplicationInsightProcessor.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
    - name: dotnet pack [Esquio.Configuration.Store]
      run: dotnet pack ./src/Esquio.Configuration.Store/Esquio.Configuration.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
    - name: dotnet pack [Esquio.EntityFrameworkCore.Store]
      run: dotnet pack ./src/Esquio.EntityFrameworkCore.Store/Esquio.EntityFrameworkCore.Store.csproj -o ./artifacts -c $BUILD_CONFIG --version-suffix "-nightly" --no-build --include-source --include-symbols
    - name: Publish nuget
      run: |
          for f in ./artifacts/*.nupkg
          do
            curl -vX PUT -u "Xabaril:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/Xabaril/
          done
      shell: bash
    # - name: setup nuget
    #   uses: NuGet/setup-nuget@v1.0.2
    #   with:
    #     nuget-version: latest
    # - name: add package repository
    #   run: nuget source Add -Config NuGet.config -Name "github" -Source https://nuget.pkg.github.com/Xabaril/index.json -UserName Xabaril -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText
    # - name: push packages
    #   run: dotnet nuget push ./artifacts/*.nupkg -s "github" -k ${{secrets.GITHUB_TOKEN}} --skip-duplicate
